name: flutter_chinese_keyboard
description: 纯Dart中文键盘实现，支持中文输入法，自带谷歌拼音词库
version: 1.0.1

homepage: https://github.com/zhangredli
repository: https://github.com/zhangredli/flutter_chinese_keyboard

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  charset: ^2.0.1
  async: ^2.11.0
  retrieval: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/assets/
